# Data cleaning and preparation

In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 10
np.set_printoptions(precision=4, suppress=True)

## Handling missing data

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
display(string_data)

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering out missing data

In [5]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
display(data)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [9]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data[4] = NA
display(data)

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [11]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
display(df)

0         1         2
0 -1.321146       NaN       NaN
1  0.590740       NaN       NaN
2 -2.337922       NaN  0.073706
3 -0.021196       NaN -0.977675
4 -0.693804 -0.302632  1.126795
5  1.527617 -0.573337  0.624627
6 -0.540385  0.221281 -0.526969

In [13]:
display(df.dropna())

0         1         2
4 -0.693804 -0.302632  1.126795
5  1.527617 -0.573337  0.624627
6 -0.540385  0.221281 -0.526969

In [14]:
df.dropna(thresh=2)

0         1         2
2 -2.337922       NaN  0.073706
3 -0.021196       NaN -0.977675
4 -0.693804 -0.302632  1.126795
5  1.527617 -0.573337  0.624627
6 -0.540385  0.221281 -0.526969

### Filling in missing data

In [15]:
df.fillna(0)

0         1         2
0 -1.321146  0.000000  0.000000
1  0.590740  0.000000  0.000000
2 -2.337922  0.000000  0.073706
3 -0.021196  0.000000 -0.977675
4 -0.693804 -0.302632  1.126795
5  1.527617 -0.573337  0.624627
6 -0.540385  0.221281 -0.526969

In [16]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.321146  0.500000  0.000000
1  0.590740  0.500000  0.000000
2 -2.337922  0.500000  0.073706
3 -0.021196  0.500000 -0.977675
4 -0.693804 -0.302632  1.126795
5  1.527617 -0.573337  0.624627
6 -0.540385  0.221281 -0.526969

In [17]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
display(df)

0         1         2
0  0.905991  1.482553  0.292273
1 -1.085709  0.693908  0.372436
2 -0.831616       NaN -0.729147
3 -0.792147       NaN -0.095736
4 -0.057623       NaN       NaN
5  0.190437       NaN       NaN

In [18]:
display(df.fillna(method='ffill'))

0         1         2
0  0.905991  1.482553  0.292273
1 -1.085709  0.693908  0.372436
2 -0.831616  0.693908 -0.729147
3 -0.792147  0.693908 -0.095736
4 -0.057623  0.693908 -0.095736
5  0.190437  0.693908 -0.095736

In [19]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.905991  1.482553  0.292273
1 -1.085709  0.693908  0.372436
2 -0.831616  0.693908 -0.729147
3 -0.792147  0.693908 -0.095736
4 -0.057623       NaN -0.095736
5  0.190437       NaN -0.095736

In [20]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Data Transformation

### Removing duplicates

In [21]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [22]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [23]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [24]:
data['v1'] = range(7)
display(data)

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [25]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [26]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming data using a function or mapping

In [27]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [29]:
lowercased = data['food'].str.lower()
display(lowercased)

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [30]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [31]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing values

In [32]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [34]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [35]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming axis indexes

In [37]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [39]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [40]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [41]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and binning

In [42]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [44]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [45]:
print(cats.codes)

[0 0 0 1 0 0 2 1 3 2 2 1]


In [46]:
print(cats.categories)

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')


In [47]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [48]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [49]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [32]:
data = np.random.rand(20)
display(data)

array([0.7477, 0.9613, 0.0084, 0.1064, 0.2987, 0.6564, 0.8098, 0.8722,
       0.9646, 0.7237, 0.6425, 0.7175, 0.4676, 0.3256, 0.4396, 0.7297,
       0.994 , 0.6769, 0.7908, 0.1709])

In [33]:
pd.cut(data, 4, precision=2)

[(0.75, 0.99], (0.75, 0.99], (0.0074, 0.25], (0.0074, 0.25], (0.25, 0.5], ..., (0.5, 0.75], (0.75, 0.99], (0.5, 0.75], (0.75, 0.99], (0.0074, 0.25]]
Length: 20
Categories (4, interval[float64]): [(0.0074, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 0.99]]

In [34]:
data = np.random.randn(1000)  # Normally distributed
cats = pd.qcut(data, 4)  # Cut into quartiles
display(cats)

[(0.62, 3.928], (-2.9499999999999997, -0.691], (-0.691, -0.0192], (-0.0192, 0.62], (-0.0192, 0.62], ..., (0.62, 3.928], (-0.691, -0.0192], (-0.691, -0.0192], (-0.691, -0.0192], (-0.691, -0.0192]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.691] < (-0.691, -0.0192] < (-0.0192, 0.62] < (0.62, 3.928]]

In [35]:
pd.value_counts(cats)

(0.62, 3.928]                    250
(-0.0192, 0.62]                  250
(-0.691, -0.0192]                250
(-2.9499999999999997, -0.691]    250
dtype: int64

In [36]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(1.289, 3.928], (-1.191, -0.0192], (-1.191, -0.0192], (-0.0192, 1.289], (-0.0192, 1.289], ..., (1.289, 3.928], (-1.191, -0.0192], (-1.191, -0.0192], (-1.191, -0.0192], (-1.191, -0.0192]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -1.191] < (-1.191, -0.0192] < (-0.0192, 1.289] < (1.289, 3.928]]

### Detecting and filtering outliers

In [37]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.022282    -0.001383    -0.055245     0.043350
std       1.008995     0.995882     0.998735     0.996658
min      -3.184377    -3.745356    -3.428254    -3.645860
25%      -0.628122    -0.697084    -0.747963    -0.600254
50%      -0.016127    -0.026381    -0.096965     0.043663
75%       0.695298     0.699046     0.622384     0.740562
max       3.525865     2.735527     3.366626     2.653656

In [56]:
col = data[2]
col[np.abs(col) > 3]

32     3.053413
821    3.066744
Name: 2, dtype: float64

In [57]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
32  -0.818788 -1.180369  3.053413  0.708176
58  -1.322334  3.306654  0.549038  0.161986
322 -0.690425 -0.359245 -1.092070 -3.609851
495 -3.020906  0.207859  0.219231  1.162063
638 -0.226639  3.110289 -1.605350 -2.415755
797  0.475605  0.867233  0.226607  3.154838
821  0.122592 -0.479898  3.066744 -0.690585
957 -0.013384  3.302258 -1.323477 -2.176356

In [58]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.016590     0.002863    -0.000722     0.004756
std       1.010218     1.034824     0.984840     0.981200
min      -3.000000    -2.637514    -2.657133    -3.000000
25%      -0.662800    -0.727587    -0.692367    -0.683323
50%       0.022703     0.025022     0.021721    -0.030576
75%       0.697024     0.680486     0.654140     0.653370
max       2.887148     3.000000     3.000000     3.000000

In [59]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0 -1.0  1.0  1.0
4  1.0 -1.0 -1.0  1.0

### Permutation and random sampling

In [11]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([3, 2, 0, 1, 4])

In [12]:
display(df)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [13]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19

In [14]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
4  16  17  18  19

In [15]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

1    7
0    5
0    5
0    5
4    4
3    6
3    6
3    6
1    7
4    4
dtype: int64

### Computing indicator/dummy variables

In [22]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [23]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [24]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('movies.dat', sep='::', header=None, names=mnames, engine='python', encoding='ISO-8859-1')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [25]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [26]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [27]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [28]:
gen = movies.genres[0]
display(gen.split('|'))
dummies.columns.get_indexer(gen.split('|'))

['Animation', "Children's", 'Comedy']

array([0, 1, 2])

In [29]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [30]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
Genre_Animation                               1
Genre_Children's                              1
                               ...             
Genre_War                                     0
Genre_Musical                                 0
Genre_Mystery                                 0
Genre_Film-Noir                               0
Genre_Western                                 0
Name: 0, Length: 21, dtype: object

In [31]:
np.random.seed(12345)
values = np.random.rand(10)
display(values)
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0